<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kieker.extension.umltransformation" nsURI="kieker.extension.umltransformation"
    nsPrefix="umlTransform">
  <eClassifiers xsi:type="ecore:EClass" name="UseCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="umlUseCases" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationRules" lowerBound="1"
        upperBound="-1" eType="#//TransformationRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" upperBound="-1"
        eType="#//Requirement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationRule" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullTransformation" eSuperTypes="#//TransformationRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="IncreaseMessageTime" eSuperTypes="#//TransformationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageName" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplyOpenWorkload" eSuperTypes="#//TransformationRule"/>
</ecore:EPackage>
